test:
  name: banking-chaincode-benchmark
  description: Throughput/latency test for banking chaincode
  workers:
    number: 5
  rounds:
    - label: open-account
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts: { tps: 50 }
      workload:
        module: workload/openAccount.js
    - label: transfer-funds
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts: { tps: 100 }
      workload:
        module: workload/transferFunds.js
    - label: approve-loan
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts: { tps: 20 }
      workload:
        module: workload/approveLoan.js
